In [1]:
%pip install pandas pyarrow scikit-learn numpy matplotlib seaborn

Requirement already satisfied: pandas in /home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages (3.0.6)
Requirement already satisfied: pyarrow in /home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages (26.0.0)
Requirement already satisfied: scikit-learn in /home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages (1.9.1)
Requirement already satisfied: numpy in /home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages (2.5.4)
Requirement already satisfied: matplotlib in /home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages (3.11.2)
Requirement already satisfied: seaborn in /home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages (0.13.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: scipy>=1.10.0 in /home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages (from scikit-learn) (1.18.1)
Requirement already satisfied: joblib>=1.4.0 in /home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages (from scikit-learn) (1.6.0)
Requirement already satisfied: narwhals>=2.0.1 in /home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages (from scikit-learn) (2.27.1)
Requirement already satisfied: threadpoolctl>=3.5.0 in /home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages (from scikit-learn) (3.7.0)
Requirement already satisfied: contourpy>=1.0.1 in /home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages (from matplotlib) (1.4.0)
Requirement already satisfied: cycler>=0.10 in /home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in /home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages (from matplotlib) (4.67.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages (from matplotlib) (1.5.1)
Requirement already satisfied: packaging>=20.0 in /home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=9 in /home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages (from matplotlib) (13.0.0)
Requirement already satisfied: pyparsing>=3 in /home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages (from matplotlib) (3.3.3)
Requirement already satisfied: cloudpickle>=3.0 in /home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages (from joblib>=1.4.0->scikit-learn) (3.1.2)
Requirement already satisfied: six>=1.5 in /home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

# Обработка Boarding

In [2]:
import pandas as pd
import numpy as np
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import LocalOutlierFactor, NearestNeighbors
from sklearn.svm import OneClassSVM
from sklearn.covariance import EllipticEnvelope

In [3]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import IsolationForest
from sklearn.neighbors import LocalOutlierFactor, NearestNeighbors
from sklearn.svm import OneClassSVM
from sklearn.covariance import EllipticEnvelope

def spies_report(X, ID, top_k=10, contamination=0.01):
    if isinstance(X, pd.DataFrame):
        X_vals = X.values
    else:
        X_vals = X
        
    if isinstance(ID, pd.Series):
        ids_arr = ID.values
    else:
        ids_arr = np.array(ID)
        
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X_vals)
    
    models = {}
    
    print("Поиск аномалий")
    
    if_model = IsolationForest(n_estimators=150, contamination=contamination, random_state=42, n_jobs=-1)
    if_model.fit(X_vals)
    if_scores = if_model.decision_function(X_vals)
    models['IsolationForest'] = -if_scores
    
    lof_model = LocalOutlierFactor(n_neighbors=20, contamination=contamination, n_jobs=-1)
    lof_model.fit(X_scaled)
    models['LOF'] = -lof_model.negative_outlier_factor_
    
    svm_model = OneClassSVM(nu=contamination, kernel='rbf', gamma='scale')
    svm_model.fit(X_scaled)
    svm_scores = svm_model.decision_function(X_scaled)
    models['OneClassSVM'] = -svm_scores
    
    try:
        ee_model = EllipticEnvelope(contamination=contamination, random_state=42)
        ee_model.fit(X_scaled)
        ee_scores = ee_model.decision_function(X_scaled)
        models['EllipticEnvelope'] = -ee_scores
    except Exception as e:
        print(f"EllipticEnvelope пропущен {e}")
        
    nn_model = NearestNeighbors(n_neighbors=20, n_jobs=-1)
    nn_model.fit(X_scaled)
    distances, _ = nn_model.kneighbors(X_scaled)
    models['KNN_Distance'] = np.mean(distances, axis=1)

    rank_records = []
    
    print("\n" + "-" * 70)
    print("Подозрительные")
    print("-" * 70)
    
    for name, scores in models.items():
        df_m = pd.DataFrame({
            'ID': ids_arr,
            'Anomaly_Score': scores
        }).sort_values(by='Anomaly_Score', ascending=False)
        
        top_df = df_m.head(top_k).copy()
        top_df['Rank'] = range(1, len(top_df) + 1)
        top_df['Model'] = name
        rank_records.append(top_df)
        
        print(f"\n--- {name} ---")
        print(top_df[['ID', 'Anomaly_Score', 'Rank']].to_string(index=False))
        print("-" * 50)
        
    all_tops = pd.concat(rank_records)
    
    all_tops['Points'] = (top_k - all_tops['Rank'] + 1)
    
    summary = all_tops.groupby('ID').agg(
        Total_Score=('Points', 'sum'),
        Models_Count=('Model', 'count'),
        Models_List=('Model', lambda x: ", ".join(x))
    ).reset_index().sort_values(by=['Total_Score', 'Models_Count'], ascending=False)
    
    return summary

In [4]:
BoardingDF = pd.read_csv("../resources/Boarding.csv", sep="|", engine="pyarrow")

aggregation_rules = {
    'PassengerFirstName': 'mean',
    'PassengerSecondName': 'mean',
    'PassengerLastName': 'mean',
    'PassengerSex': 'first',
    'PassengerAge': 'first',
    'PassportSeriesLeft': 'first',
    'PassportSeriesRight': 'first',
    
    'TicketNumber': 'count',
    'FlightTime': 'mean',
    'FlightNumber': 'mean',
    'CodeShare': 'mean',
    'Destination': 'max',
    
    'boardFlightMatch': 'mean',
    'OperatFlightMatch': 'mean',
    'PassBoardingMatch': 'mean',
    'SirenaBoardingMatch': 'mean',
    
    'BaggageTransit': 'sum',
    'BaggageDelayed': 'sum',
    'BaggageRegistered': 'sum',
    
    'Flight_DayOfWeek': 'mean',
    'Flight_Month': 'nunique'
}

passenger_df = BoardingDF.groupby('Document').agg(aggregation_rules).reset_index()

IDS = passenger_df['Document'].copy()
X = passenger_df.drop(columns=['Document'])

spies_report(X, IDS)

Поиск аномалий

/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:793: UserWarning: The covariance matrix associated to your dataset is not full rank
  warnings.warn(

----------------------------------------------------------------------
Подозрительные
----------------------------------------------------------------------

--- IsolationForest ---
         ID  Anomaly_Score  Rank
5293 500602       0.101237     1
0977 338850       0.096909     2
1311 440150       0.086798     3
8176 892394       0.086109     4
1181 213093       0.083668     5
1379 543723       0.083184     6
1548 113497       0.079667     7
0185 106233       0.078386     8
6937 933652       0.077325     9
2294 770067       0.076448    10
--------------------------------------------------

--- LOF ---
         ID  Anomaly_Score  Rank
2420 116077       1.637272     1
1028 207088       1.618745     2
8537 137481       1.606997     3
5405 898615       1.595745     4
7544 655717       1.585977     5
0977 338850       1.579689     6
1530 068060       1.578621     7
1810 413944       1.577679     8
4076 926383       1.566683     9
7314 180345       1.564469    10
--------------------------------------------------

--- OneClassSVM ---
         ID  Anomaly_Score  Rank
0977 338850      10.170953     1
5293 500602      10.011625     2
8816 864475       8.996844     3
3050 260754       8.975053     4
6038 903499       8.607663     5
4992 905133       8.322026     6
0185 106233       8.175608     7
1548 113497       7.219678     8
7544 655717       7.088490     9
1439 758058       7.008115    10
--------------------------------------------------

--- EllipticEnvelope ---
         ID  Anomaly_Score  Rank
4992 905133    2648.806592     1
4013 363390    2636.336058     2
3101 754432    2629.483223     3
6689 332299    2629.261432     4
9504 642696    2629.116360     5
8211 370516    2629.030034     6
7006 039700    2628.520343     7
0801 171124    2627.875893     8
3487 135982    2627.169281     9
5817 794453    2627.031749    10
--------------------------------------------------

--- KNN_Distance ---
         ID  Anomaly_Score  Rank
0977 338850       6.941789     1
5293 500602       6.851376     2
3050 260754       6.330938     3
0185 106233       6.298094     4
1028 207088       6.145347     5
2326 484258       6.041866     6
2006 962150       5.918367     7
4992 905133       5.912201     8
6038 903499       5.854623     9
8816 864475       5.812302    10
--------------------------------------------------

,ID,Total_Score,Models_Count,Models_List
2,0977 338850,34,4,"IsolationForest, LOF, OneClassSVM, KNN_Distance"
21,5293 500602,28,3,"IsolationForest, OneClassSVM, KNN_Distance"
20,4992 905133,18,3,"OneClassSVM, EllipticEnvelope, KNN_Distance"
3,1028 207088,15,2,"LOF, KNN_Distance"
15,3050 260754,15,2,"OneClassSVM, KNN_Distance"
0,0185 106233,14,3,"IsolationForest, OneClassSVM, KNN_Distance"
14,2420 116077,10,1,LOF
33,8816 864475,9,2,"OneClassSVM, KNN_Distance"
18,4013 363390,9,1,EllipticEnvelope
24,6038 903499,8,2,"OneClassSVM, KNN_Distance"
29,7544 655717,8,2,"LOF, OneClassSVM"
5,1311 440150,8,1,IsolationForest
16,3101 754432,8,1,EllipticEnvelope
32,8537 137481,8,1,LOF
9,1548 113497,7,2,"IsolationForest, OneClassSVM"
22,5405 898615,7,1,LOF
25,6689 332299,7,1,EllipticEnvelope
30,8176 892394,7,1,IsolationForest
4,1181 213093,6,1,IsolationForest
34,9504 642696,6,1,EllipticEnvelope
6,1379 543723,5,1,IsolationForest
13,2326 484258,5,1,KNN_Distance
31,8211 370516,5,1,EllipticEnvelope
8,1530 068060,4,1,LOF
11,2006 962150,4,1,KNN_Distance
27,7006 039700,4,1,EllipticEnvelope
1,0801 171124,3,1,EllipticEnvelope
10,1810 413944,3,1,LOF
17,3487 135982,2,1,EllipticEnvelope
19,4076 926383,2,1,LOF
26,6937 933652,2,1,IsolationForest
7,1439 758058,1,1,OneClassSVM
12,2294 770067,1,1,IsolationForest
23,5817 794453,1,1,EllipticEnvelope
28,7314 180345,1,1,LOF

In [5]:
SirenaDF = pd.read_csv("../resources/sirena.csv", sep="|")
aggregation_rules = {
    'FlightCode': 'mean',
    'SirenaBoardingMatch': 'mean',
    'SirenaFlightsMatch': 'mean',
    
    'LastName': 'first',
    'FirstName': 'first',
    'SecondName': 'first',
    
    'HasBirthDate': 'first',
    'PassengerAge': 'first',
    
    'Flight_DayOfWeek': 'mean',
    'Flight_Month': 'nunique',
    'DepartTimeMinutes': 'mean',
    
    'TrvCls_A': 'sum',
    'TrvCls_J': 'sum',
    'TrvCls_P': 'sum',
    'TrvCls_Y': 'sum'
}

passenger_df = SirenaDF.groupby('PaxName').agg(aggregation_rules).reset_index()

IDS = passenger_df['PaxName'].copy()
X = passenger_df.drop(columns=['PaxName'])

sp = spies_report(X, IDS)
sp.to_csv("sirena.csv", sep="|", index="false")
display(sp)

Поиск аномалий

/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:793: UserWarning: The covariance matrix associated to your dataset is not full rank
  warnings.warn(

----------------------------------------------------------------------
Подозрительные
----------------------------------------------------------------------

--- IsolationForest ---
                           ID  Anomaly_Score  Rank
 DANILOVICH ALEKSEI PARAMONOV       0.119985     1
    DANILOVNA EMILIIA OZEROVA       0.103766     2
  ARSENEVICH GRIGORII KISELEV       0.102570     3
   ARSENEVNA IASMINA DAVYDOVA       0.101167     4
    LVOVICH ALEKSANDR KHROMOV       0.091188     5
 VLADISLAVOVNA KARINA NAUMOVA       0.089444     6
    DANILOVNA ADELINA SURKOVA       0.089418     7
     SAVVOVNA OLESIA MURAVEVA       0.089342     8
BOGDANOVNA NADEZHDA MERKULOVA       0.087635     9
   AIDAROVNA LIANA PLOTNIKOVA       0.085174    10
--------------------------------------------------

--- LOF ---
                           ID  Anomaly_Score  Rank
    GERMANOVNA ALENA CHERNYKH       2.121500     1
   ANDREEVICH GORDEI CHERNYKH       2.116583     2
  DANILOVNA VASILISA CHERNYKH       2.038425     3
     PLATONOVNA KIRA DANILOVA       2.025996     4
    ROBERTOVNA ALLA SHEVTSOVA       1.995589     5
    DANILOVNA ZARINA CHERNYKH       1.981038     6
 DANILOVNA EKATERINA CHERNYKH       1.963526     7
    ARSENEVICH ARTEM CHERNYKH       1.960826     8
ARSENEVICH VLADISLAV CHERNYKH       1.933488     9
      SEMENOVICH NAZAR SYCHEV       1.908463    10
--------------------------------------------------

--- OneClassSVM ---
                           ID  Anomaly_Score  Rank
      SEMENOVICH NAZAR SYCHEV      10.325609     1
     PLATONOVNA KIRA DANILOVA      10.181571     2
    LVOVICH ALEKSANDR KHROMOV       9.921593     3
    ROBERTOVNA ALLA SHEVTSOVA       9.712437     4
    ARSENEVICH RADMIR GOLUBEV       9.530085     5
 DANILOVICH ALEKSEI PARAMONOV       9.349157     6
ALEKSANDROVICH ALEKSEI MAKEEV       8.802567     7
   ZAKHAROVNA VARVARA MINAEVA       8.549794     8
  DANILOVNA VASILISA CHERNYKH       8.472141     9
    SERGEEVICH SAVVA BELOUSOV       8.399910    10
--------------------------------------------------

--- EllipticEnvelope ---
                            ID  Anomaly_Score  Rank
ARSENEVNA VERONIKA KHARITONOVA     108.363918     1
     ARSENEVNA KSENIIA IASHINA      83.876157     2
     ARSENEVICH RADMIR GOLUBEV      80.751396     3
    ARSENEVNA IASMINA DAVYDOVA      80.524742     4
       ARSENEVNA ZLATA EFIMOVA      77.528791     5
        ARSENEVNA INNA KUZMINA      75.914417     6
       ARSENEVNA VERA KOROVINA      73.345507     7
  ARSENEVNA KAROLINA GOROKHOVA      66.373092     8
      ARSENEVNA LIANA KRIUKOVA      66.089223     9
  ARSENEVNA TATIANA KORSHUNOVA      62.257736    10
--------------------------------------------------

--- KNN_Distance ---
                           ID  Anomaly_Score  Rank
      SEMENOVICH NAZAR SYCHEV       7.222057     1
    LVOVICH ALEKSANDR KHROMOV       6.774386     2
     PLATONOVNA KIRA DANILOVA       6.755691     3
    ROBERTOVNA ALLA SHEVTSOVA       6.459451     4
    ARSENEVICH RADMIR GOLUBEV       6.382078     5
 DANILOVICH ALEKSEI PARAMONOV       6.239847     6
ALEKSANDROVICH ALEKSEI MAKEEV       5.860763     7
  DANILOVNA VASILISA CHERNYKH       5.740645     8
    SERGEEVICH SAVVA BELOUSOV       5.595921     9
   ARSENEVNA IASMINA DAVYDOVA       5.411860    10
--------------------------------------------------

,ID,Total_Score,Models_Count,Models_List
25,PLATONOVNA KIRA DANILOVA,24,3,"LOF, OneClassSVM, KNN_Distance"
24,LVOVICH ALEKSANDR KHROMOV,23,3,"IsolationForest, OneClassSVM, KNN_Distance"
28,SEMENOVICH NAZAR SYCHEV,21,3,"LOF, OneClassSVM, KNN_Distance"
5,ARSENEVICH RADMIR GOLUBEV,20,3,"OneClassSVM, EllipticEnvelope, KNN_Distance"
17,DANILOVICH ALEKSEI PARAMONOV,20,3,"IsolationForest, OneClassSVM, KNN_Distance"
26,ROBERTOVNA ALLA SHEVTSOVA,20,3,"LOF, OneClassSVM, KNN_Distance"
7,ARSENEVNA IASMINA DAVYDOVA,15,3,"IsolationForest, EllipticEnvelope, KNN_Distance"
21,DANILOVNA VASILISA CHERNYKH,13,3,"LOF, OneClassSVM, KNN_Distance"
14,ARSENEVNA VERONIKA KHARITONOVA,10,1,EllipticEnvelope
23,GERMANOVNA ALENA CHERNYKH,10,1,LOF
2,ANDREEVICH GORDEI CHERNYKH,9,1,LOF
10,ARSENEVNA KSENIIA IASHINA,9,1,EllipticEnvelope
20,DANILOVNA EMILIIA OZEROVA,9,1,IsolationForest
1,ALEKSANDROVICH ALEKSEI MAKEEV,8,2,"OneClassSVM, KNN_Distance"
4,ARSENEVICH GRIGORII KISELEV,8,1,IsolationForest
15,ARSENEVNA ZLATA EFIMOVA,6,1,EllipticEnvelope
8,ARSENEVNA INNA KUZMINA,5,1,EllipticEnvelope
22,DANILOVNA ZARINA CHERNYKH,5,1,LOF
30,VLADISLAVOVNA KARINA NAUMOVA,5,1,IsolationForest
13,ARSENEVNA VERA KOROVINA,4,1,EllipticEnvelope
18,DANILOVNA ADELINA SURKOVA,4,1,IsolationForest
19,DANILOVNA EKATERINA CHERNYKH,4,1,LOF
29,SERGEEVICH SAVVA BELOUSOV,3,2,"OneClassSVM, KNN_Distance"
3,ARSENEVICH ARTEM CHERNYKH,3,1,LOF
9,ARSENEVNA KAROLINA GOROKHOVA,3,1,EllipticEnvelope
27,SAVVOVNA OLESIA MURAVEVA,3,1,IsolationForest
31,ZAKHAROVNA VARVARA MINAEVA,3,1,OneClassSVM
6,ARSENEVICH VLADISLAV CHERNYKH,2,1,LOF
11,ARSENEVNA LIANA KRIUKOVA,2,1,EllipticEnvelope
16,BOGDANOVNA NADEZHDA MERKULOVA,2,1,IsolationForest
0,AIDAROVNA LIANA PLOTNIKOVA,1,1,IsolationForest
12,ARSENEVNA TATIANA KORSHUNOVA,1,1,EllipticEnvelope

In [6]:
Flights_Boarding_DF = pd.read_csv("../resources/flights_boarding.csv", sep="|")

if 'FlightTime' in Flights_Boarding_DF.columns and Flights_Boarding_DF['FlightTime'].dtype == object:
    ft = Flights_Boarding_DF['FlightTime'].astype(str)
    Flights_Boarding_DF['FlightTimeMinutes'] = (
        ft.str.slice(0, 2).astype(float) * 60 +
        ft.str.slice(3, 5).astype(float)
    )

aggregation_rules = {
    'Codeshare': 'mean',
    'Flight': 'mean',
    'PassengerFirstName': 'mean',
    'PassengerSecondName': 'mean',
    'PassengerLastName': 'mean',
    'PassengerSex': 'first',
    'BookingCode': 'mean',
    'TicketNumber': 'mean',
    'CodeShare': 'mean',
    'Flight_DayOfWeek': 'mean',
    'Flight_Month': 'nunique',
    'Airport': 'mean',
    'City': 'mean',
    'Country': 'mean',
    'BaggageTransit': 'sum',
    'BaggageDelayed': 'sum',
    'BaggageRegistered': 'sum'
}

passenger_df = Flights_Boarding_DF.groupby('PassengerDocument').agg(aggregation_rules).reset_index()

IDS = passenger_df['PassengerDocument'].copy()
X = passenger_df.drop(columns=['PassengerDocument'])

sp = spies_report(X, IDS)
sp.to_csv("flights_boarding.csv", sep="|", index=False)
display(sp)

Поиск аномалий

/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:793: UserWarning: The covariance matrix associated to your dataset is not full rank
  warnings.warn(

----------------------------------------------------------------------
Подозрительные
----------------------------------------------------------------------

--- IsolationForest ---
         ID  Anomaly_Score  Rank
0016 277417       0.061421     1
5058 032032       0.055902     2
2908 898279       0.055135     3
1477 356912       0.054759     4
8483 273783       0.054420     5
5294 379207       0.052793     6
2211 426963       0.051903     7
2937 910860       0.051182     8
3381 195015       0.050705     9
2874 843094       0.049283    10
--------------------------------------------------

--- LOF ---
         ID  Anomaly_Score  Rank
6025 719450       2.983550     1
2468 127099       2.287839     2
8917 305885       2.285872     3
0903 193247       2.266384     4
9967 524999       2.235298     5
8048 395178       2.067222     6
9530 022510       2.049697     7
6561 078609       1.978905     8
8205 801009       1.925578     9
8007 894293       1.870297    10
--------------------------------------------------

--- OneClassSVM ---
         ID  Anomaly_Score  Rank
8007 894293      11.950453     1
0241 175441      11.196116     2
2908 898279      11.185102     3
2211 426963      11.041793     4
3192 122949      10.016697     5
1181 213093       9.487266     6
5058 032032       9.422792     7
6955 916298       8.009075     8
7986 411256       7.921452     9
6121 645946       7.562924    10
--------------------------------------------------

--- EllipticEnvelope ---
         ID  Anomaly_Score  Rank
8007 894293    3846.195559     1
6955 916298    2761.460393     2
1978 571330    2288.018256     3
8639 152338    2224.678952     4
5058 032032    2205.304458     5
8020 071651    2130.031081     6
2671 246091    2011.389445     7
3710 150996    1883.381258     8
0241 175441    1874.206615     9
2211 426963    1869.412292    10
--------------------------------------------------

--- KNN_Distance ---
         ID  Anomaly_Score  Rank
8007 894293       6.395874     1
2908 898279       5.901760     2
0241 175441       5.864321     3
2211 426963       5.812115     4
5058 032032       5.218095     5
3192 122949       5.190281     6
1181 213093       5.162485     7
6121 645946       4.911894     8
7986 411256       4.672370     9
5153 193431       4.663281    10
--------------------------------------------------

,ID,Total_Score,Models_Count,Models_List
23,8007 894293,31,4,"LOF, OneClassSVM, EllipticEnvelope, KNN_Distance"
15,5058 032032,25,4,"IsolationForest, OneClassSVM, EllipticEnvelope..."
10,2908 898279,25,3,"IsolationForest, OneClassSVM, KNN_Distance"
6,2211 426963,19,4,"IsolationForest, OneClassSVM, EllipticEnvelope..."
1,0241 175441,19,3,"OneClassSVM, EllipticEnvelope, KNN_Distance"
21,6955 916298,12,2,"OneClassSVM, EllipticEnvelope"
12,3192 122949,11,2,"OneClassSVM, KNN_Distance"
0,0016 277417,10,1,IsolationForest
18,6025 719450,10,1,LOF
3,1181 213093,9,2,"OneClassSVM, KNN_Distance"
7,2468 127099,9,1,LOF
5,1978 571330,8,1,EllipticEnvelope
29,8917 305885,8,1,LOF
2,0903 193247,7,1,LOF
4,1477 356912,7,1,IsolationForest
28,8639 152338,7,1,EllipticEnvelope
27,8483 273783,6,1,IsolationForest
31,9967 524999,6,1,LOF
17,5294 379207,5,1,IsolationForest
24,8020 071651,5,1,EllipticEnvelope
25,8048 395178,5,1,LOF
19,6121 645946,4,2,"OneClassSVM, KNN_Distance"
22,7986 411256,4,2,"OneClassSVM, KNN_Distance"
8,2671 246091,4,1,EllipticEnvelope
30,9530 022510,4,1,LOF
11,2937 910860,3,1,IsolationForest
14,3710 150996,3,1,EllipticEnvelope
20,6561 078609,3,1,LOF
13,3381 195015,2,1,IsolationForest
26,8205 801009,2,1,LOF
9,2874 843094,1,1,IsolationForest
16,5153 193431,1,1,KNN_Distance

In [7]:
df = pd.read_csv("../resources/boarding_operational.csv", sep="|")

aggregation_rules = {
    'PassengerFirstName': 'mean',
    'PassengerSecondName': 'mean',
    'PassengerLastName': 'mean',
    'PassengerSex': 'first',
    'BookingCode': 'mean',
    'FlightTime': 'mean',
    'FlightNumber': 'mean',
    'CodeShare': 'mean',
    'boardFlightMatch': 'mean',
    'Fare': 'mean',
    'BaggageTransit': 'sum',
    'BaggageDelayed': 'sum',
    'BaggageRegistered': 'sum',
    'PassengerAge': 'first',
    'ClassY': 'sum',
    'ClassJ': 'sum',
    'ClassP': 'sum',
    'FF_Airline_SU': 'sum',
    'FF_Airline_KE': 'sum',
    'FF_Airline_DT': 'sum',
    'Airport': 'mean'
}

passenger_df = df.groupby('PassengerDocument').agg(aggregation_rules).reset_index()

IDS = passenger_df['PassengerDocument'].copy()
X = passenger_df.drop(columns=['PassengerDocument'])

sp = spies_report(X, IDS)
sp.to_csv("boarding_operational.csv", sep="|", index=False)
display(sp)

Поиск аномалий

/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:188: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-49.597773445909390 > -107.166608332999985). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn(
/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:188: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-107.157849462181858 > -109.849616018034823). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn(
/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:188: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-45.769814703404755 > -105.947505177965283). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn(
/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:188: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-45.564929054149772 > -106.908681536310098). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn(
/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:188: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-43.657593004942960 > -105.270608455676538). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn(
/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:188: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-43.487367545866327 > -104.646796315749953). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn(
/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:188: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-43.720993836779812 > -106.066273235617118). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn(
/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:188: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-44.320939418203416 > -106.089939832207563). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn(
/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:188: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-41.279893348196765 > -103.966641069335239). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn(
/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:188: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-40.898095240457607 > -103.361867700603554). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn(
/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:188: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-41.324344184256198 > -103.183722173843890). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn(
/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:188: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-40.961576230450063 > -104.089534635416470). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn(
/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:188: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-40.909289474309091 > -103.185491128319086). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn(
/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:188: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-41.051972835872483 > -103.251272464959342). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn(
/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:188: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-41.191613275678982 > -103.791774752771460). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn(
/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:188: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-41.163139674573756 > -104.252817012486943). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn(
/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:188: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-44.958735473907772 > -107.142137421505353). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn(
/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:188: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-43.893861672685546 > -106.790685239656057). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn(
/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:188: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-42.873642722345437 > -105.562411485887921). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn(
/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:188: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-43.623406100502869 > -106.036979631158289). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn(
/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:188: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-45.546985124557999 > -105.492716659462033). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn(
/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:188: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-45.925932271417921 > -107.583532950539706). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn(
/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:188: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-47.192815458467038 > -107.577730394726004). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn(
/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:188: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-46.948403670873041 > -107.734481356094278). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn(
/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:188: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-47.905927730391682 > -109.120349366868908). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn(
/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:188: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-47.488925003533645 > -108.132958270271530). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn(
/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:188: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-45.668212043282011 > -107.305146702063453). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn(
/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:188: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-45.717942353019261 > -107.910326951818078). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn(
/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:188: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-47.431773503781123 > -107.827846469921838). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn(
/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:188: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-47.406914613231450 > -108.344163593947997). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn(
/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:188: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-45.434994545125718 > -107.709572288135618). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn(
/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:188: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-44.492284567684493 > -106.972203202448796). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn(
/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:188: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-46.635437042263582 > -107.996300114760786). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn(
/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:188: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-46.941299352019428 > -108.860547510443439). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn(
/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:188: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-46.488985683590542 > -107.386387987128117). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn(
/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:188: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-50.774669855293553 > -111.132641709299733). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn(
/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:188: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-47.135761544955272 > -106.735828370676458). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn(
/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:188: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-46.198686014765720 > -107.624575469761027). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn(
/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:188: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-46.689168547804080 > -107.213956741175338). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn(
/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:188: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-47.443231335568569 > -108.104586641574855). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn(
/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:188: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-47.358287678401545 > -107.252244532174814). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn(
/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:188: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-46.196447566836021 > -106.737719125930070). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn(
/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:188: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-43.501148156232617 > -104.428827650805914). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn(
/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:188: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-43.466155317730340 > -105.792138072064475). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn(
/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:188: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-45.892334886889181 > -105.198072060497395). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn(
/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:188: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-43.751628872145062 > -105.224714894821872). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn(
/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:188: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-43.671506009712871 > -104.397663704193846). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn(
/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:188: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-43.494189112550949 > -105.722716747854960). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn(
/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:188: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-44.327294781059031 > -105.156318196006339). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn(
/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:188: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-43.444146263123770 > -106.663188032185715). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn(
/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:188: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-43.329363104369314 > -104.917816448345945). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn(
/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:188: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-50.466532241824332 > -108.599136445390528). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn(
/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:188: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-50.613816090985566 > -107.517539451426259). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn(
/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:188: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-49.176303194223415 > -108.229082231924849). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn(
/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:188: RuntimeWarning: Determinant has increased; this should not happen: log(det) > log(previous_det) (-46.393415338183324 > -106.821407107870399). You may want to try with a higher value of support_fraction (current value: 0.503).
  warnings.warn(

----------------------------------------------------------------------
Подозрительные
----------------------------------------------------------------------

--- IsolationForest ---
         ID  Anomaly_Score  Rank
2211 426963       0.073928     1
5294 379207       0.070831     2
1889 427649       0.070751     3
5058 032032       0.066261     4
1477 356912       0.066004     5
7043 974968       0.065728     6
1647 595790       0.065617     7
8421 352449       0.065472     8
3381 195015       0.065052     9
6695 351151       0.064812    10
--------------------------------------------------

--- LOF ---
         ID  Anomaly_Score  Rank
8007 894293       2.845137     1
8421 352449       2.052325     2
3505 707537       2.032051     3
0241 175441       1.859861     4
5879 481501       1.852779     5
3710 150996       1.820879     6
7767 309620       1.809874     7
2211 426963       1.783809     8
3941 182395       1.745868     9
4819 170172       1.741885    10
--------------------------------------------------

--- OneClassSVM ---
         ID  Anomaly_Score  Rank
8007 894293      11.728141     1
8421 352449      11.685956     2
3710 150996      11.282391     3
2211 426963      10.876504     4
0241 175441      10.870993     5
4819 170172       9.945088     6
1451 820823       9.634833     7
7994 786671       9.351714     8
0108 245003       9.036507     9
8639 152338       8.563599    10
--------------------------------------------------

--- EllipticEnvelope ---
         ID  Anomaly_Score  Rank
8007 894293    4522.453448     1
1978 571330    2781.789573     2
0241 175441    2698.286503     3
3272 118132    2691.407533     4
3710 150996    2317.850394     5
4819 170172    2104.746238     6
8020 071651    2104.741818     7
2211 426963    2050.132116     8
9271 651446    1928.304445     9
8421 352449    1914.055739    10
--------------------------------------------------

--- KNN_Distance ---
         ID  Anomaly_Score  Rank
8007 894293      12.596854     1
8421 352449      11.150054     2
3710 150996       8.729691     3
2211 426963       8.363350     4
0241 175441       7.858297     5
4819 170172       7.415602     6
7994 786671       7.043592     7
1451 820823       6.886630     8
6121 645946       6.471959     9
5153 193431       6.402745    10
--------------------------------------------------

,ID,Total_Score,Models_Count,Models_List
23,8007 894293,40,4,"LOF, OneClassSVM, EllipticEnvelope, KNN_Distance"
25,8421 352449,31,5,"IsolationForest, LOF, OneClassSVM, EllipticEnv..."
7,2211 426963,30,5,"IsolationForest, LOF, OneClassSVM, EllipticEnv..."
1,0241 175441,27,4,"LOF, OneClassSVM, EllipticEnvelope, KNN_Distance"
11,3710 150996,27,4,"LOF, OneClassSVM, EllipticEnvelope, KNN_Distance"
13,4819 170172,16,4,"LOF, OneClassSVM, EllipticEnvelope, KNN_Distance"
6,1978 571330,9,1,EllipticEnvelope
16,5294 379207,9,1,IsolationForest
5,1889 427649,8,1,IsolationForest
10,3505 707537,8,1,LOF
2,1451 820823,7,2,"OneClassSVM, KNN_Distance"
22,7994 786671,7,2,"OneClassSVM, KNN_Distance"
8,3272 118132,7,1,EllipticEnvelope
14,5058 032032,7,1,IsolationForest
3,1477 356912,6,1,IsolationForest
17,5879 481501,6,1,LOF
20,7043 974968,5,1,IsolationForest
4,1647 595790,4,1,IsolationForest
21,7767 309620,4,1,LOF
24,8020 071651,4,1,EllipticEnvelope
0,0108 245003,2,1,OneClassSVM
9,3381 195015,2,1,IsolationForest
12,3941 182395,2,1,LOF
18,6121 645946,2,1,KNN_Distance
27,9271 651446,2,1,EllipticEnvelope
15,5153 193431,1,1,KNN_Distance
19,6695 351151,1,1,IsolationForest
26,8639 152338,1,1,OneClassSVM

In [8]:
df = pd.read_csv("../resources/pass_boarding.csv", sep="|")
aggregation_rules = {
    'Очередь_регистрации': 'mean',
    'PassengerFirstName': 'mean',
    'PassengerSecondName': 'mean',
    'PassengerLastName': 'mean',
    'PassengerSex': 'first',
    'BookingCode': 'mean',
    'FlightTime': 'mean',
    'FlightNumber': 'mean',
    'CodeShare': 'mean',
    'Destination': 'mean',
    'boardFlightMatch': 'mean',
    'OperatFlightMatch': 'mean',
    'PassengerAge': 'first',
    'PassportSeriesLeft': 'first',
    'PassportSeriesRight': 'first',
    'TicketNumber': 'sum',
    'BaggageTransit': 'sum',
    'BaggageDelayed': 'sum',
    'BaggageRegistered': 'sum',
    'Flight_DayOfWeek': 'mean',
    'Flight_Month': 'nunique',
    'ClassY': 'sum',
    'ClassJ': 'sum',
    'ClassP': 'sum',
    'City': 'mean',
    'Airport': 'mean',
    'BonusCard': 'max'
}

passenger_df = df.groupby('Document').agg(aggregation_rules).reset_index()

IDS = passenger_df['Document'].copy()
X = passenger_df.drop(columns=['Document'])

sp = spies_report(X, IDS)
sp.to_csv("pass_boarding.csv", sep="|", index=False)
display(sp)

Поиск аномалий

/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:793: UserWarning: The covariance matrix associated to your dataset is not full rank
  warnings.warn(

----------------------------------------------------------------------
Подозрительные
----------------------------------------------------------------------

--- IsolationForest ---
         ID  Anomaly_Score  Rank
0389 510918       0.078760     1
5293 500602       0.067232     2
8560 808153       0.062200     3
5462 603688       0.060311     4
2294 770067       0.059387     5
6298 955090       0.059257     6
4592 146429       0.055290     7
4959 862296       0.052944     8
0977 338850       0.047693     9
9074 223766       0.047514    10
--------------------------------------------------

--- LOF ---
         ID  Anomaly_Score  Rank
8296 978071       1.629960     1
0548 488693       1.591156     2
9579 067482       1.554825     3
9777 886483       1.540321     4
5293 500602       1.527368     5
1770 182105       1.512739     6
6424 452421       1.500467     7
9679 942167       1.498753     8
7749 971945       1.495225     9
0974 927924       1.458141    10
--------------------------------------------------

--- OneClassSVM ---
         ID  Anomaly_Score  Rank
5293 500602       2.069083     1
9579 067482       1.881742     2
1381 919028       1.525949     3
6477 314549       1.243186     4
7260 430301       1.081325     5
6724 620157       1.008934     6
0900 807116       0.915548     7
6298 955090       0.910754     8
0389 510918       0.888961     9
8293 513568       0.835425    10
--------------------------------------------------

--- EllipticEnvelope ---
         ID  Anomaly_Score  Rank
1381 919028    5780.278774     1
4325 574940    5677.405703     2
8296 978071    5666.092125     3
0548 488693    5664.931985     4
2321 908313    5663.046720     5
0591 973162    5661.936099     6
6424 452421    5659.513694     7
2124 673315    5655.392632     8
6790 253421    5655.223818     9
0357 213220    5628.947341    10
--------------------------------------------------

--- KNN_Distance ---
         ID  Anomaly_Score  Rank
5293 500602       8.849226     1
1381 919028       8.088174     2
9579 067482       7.752999     3
6477 314549       7.331971     4
2276 685137       7.306984     5
6298 955090       7.218611     6
7260 430301       7.182448     7
0548 488693       6.952687     8
0357 213220       6.877613     9
8296 978071       6.825409    10
--------------------------------------------------

,ID,Total_Score,Models_Count,Models_List
16,5293 500602,35,4,"IsolationForest, LOF, OneClassSVM, KNN_Distance"
7,1381 919028,27,3,"OneClassSVM, EllipticEnvelope, KNN_Distance"
29,9579 067482,25,3,"LOF, OneClassSVM, KNN_Distance"
2,0548 488693,19,3,"LOF, EllipticEnvelope, KNN_Distance"
26,8296 978071,19,3,"LOF, EllipticEnvelope, KNN_Distance"
20,6477 314549,14,2,"OneClassSVM, KNN_Distance"
18,6298 955090,13,3,"IsolationForest, OneClassSVM, KNN_Distance"
1,0389 510918,12,2,"IsolationForest, OneClassSVM"
23,7260 430301,10,2,"OneClassSVM, KNN_Distance"
13,4325 574940,9,1,EllipticEnvelope
19,6424 452421,8,2,"LOF, EllipticEnvelope"
27,8560 808153,8,1,IsolationForest
17,5462 603688,7,1,IsolationForest
31,9777 886483,7,1,LOF
10,2276 685137,6,1,KNN_Distance
11,2294 770067,6,1,IsolationForest
12,2321 908313,6,1,EllipticEnvelope
3,0591 973162,5,1,EllipticEnvelope
8,1770 182105,5,1,LOF
21,6724 620157,5,1,OneClassSVM
4,0900 807116,4,1,OneClassSVM
14,4592 146429,4,1,IsolationForest
0,0357 213220,3,2,"EllipticEnvelope, KNN_Distance"
9,2124 673315,3,1,EllipticEnvelope
15,4959 862296,3,1,IsolationForest
30,9679 942167,3,1,LOF
6,0977 338850,2,1,IsolationForest
22,6790 253421,2,1,EllipticEnvelope
24,7749 971945,2,1,LOF
5,0974 927924,1,1,LOF
25,8293 513568,1,1,OneClassSVM
28,9074 223766,1,1,IsolationForest

In [9]:
df = pd.read_csv("../resources/loyalty_operational.csv", sep="|")

aggregation_rules = {
    'FirstName': 'mean',
    'LastName': 'mean',
    'Departure': 'mean',
    'Arrival': 'mean',
    'FF_Number': 'mean',
    'OperatFlightMatch': 'mean',
    'FlightOperationalMatch': 'mean',
    'ClassY': 'sum',
    'ClassJ': 'sum',
    'ClassP': 'sum',
    'BonusProgramA': 'sum',
    'BonusProgramD': 'sum',
    'BonusProgramK': 'sum',
    'Flight_DayOfWeek': 'mean',
    'Flight_Month': 'nunique',
    'Airport': 'mean',
    'FF_Airline_SU': 'sum',
    'FF_Airline_KE': 'sum',
    'FF_Airline_DT': 'sum'
}

passenger_df = df.groupby('Name').agg(aggregation_rules).reset_index()

IDS = passenger_df['Name'].copy()
X = passenger_df.drop(columns=['Name'])

sp = spies_report(X, IDS)
sp.to_csv("loyalty_operational.csv", sep="|", index=False)
display(sp)

Поиск аномалий

----------------------------------------------------------------------
Подозрительные
----------------------------------------------------------------------

--- IsolationForest ---
                ID  Anomaly_Score  Rank
     ALLA RUSAKOVA       0.086187     1
     PETR KOCHETOV       0.084620     2
      VLAD GOLUBEV       0.080347     3
      OLEG ANTIPOV       0.073350     4
   DIANA SOFRONOVA       0.070824     5
   MILENA ZAYTSEVA       0.069915     6
    RADMIR KORNEEV       0.068503     7
      SAVVA MARKOV       0.068409     8
     MADINA LOSEVA       0.068329     9
ANZHELIKA BELIKOVA       0.065095    10
--------------------------------------------------

--- LOF ---
               ID  Anomaly_Score  Rank
TIMOFEY DRUZHININ       2.204499     1
  MARINA GORELOVA       2.155499     2
   VADIM PLATONOV       1.959899     3
    PETR KOCHETOV       1.923482     4
  ULIANA EROFEEVA       1.877531     5
    LILIYA ZOTOVA       1.809951     6
YASMINA ANISIMOVA       1.804946     7
FEDOR SEREBRYAKOV       1.794495     8
    INNA CHERNYKH       1.792260     9
  EMIL' SHESTAKOV       1.786728    10
--------------------------------------------------

--- OneClassSVM ---
                 ID  Anomaly_Score  Rank
  TIMOFEY DRUZHININ       6.201109     1
      PETR KOCHETOV       6.170333     2
    MARINA GORELOVA       6.158031     3
       OLEG ANTIPOV       5.913006     4
IAROSLAVA SNEGIREVA       5.652647     5
    DIANA SOFRONOVA       5.628639     6
     TIKHON ZELENIN       5.576325     7
       SAVVA MARKOV       5.528182     8
      ALLA RUSAKOVA       4.840998     9
       VLAD GOLUBEV       4.764598    10
--------------------------------------------------

--- EllipticEnvelope ---
               ID  Anomaly_Score  Rank
  MARINA GORELOVA   23035.853496     1
TIMOFEY DRUZHININ   19704.963023     2
  MARINA MURAVEVA   14961.992507     3
     OLEG ANTIPOV   13562.959279     4
  ALENA PETUKHOVA   12730.542482     5
    PETR KOCHETOV   12172.833731     6
  DIANA SOFRONOVA   10329.745340     7
  VERA BOGOMOLOVA   10087.967407     8
EDUARD PAVLOVSKII    9755.136374     9
  NIKA CHERNYAEVA    9486.069757    10
--------------------------------------------------

--- KNN_Distance ---
                 ID  Anomaly_Score  Rank
  TIMOFEY DRUZHININ      13.112153     1
      PETR KOCHETOV      10.825477     2
    MARINA GORELOVA      10.525921     3
       OLEG ANTIPOV       8.648359     4
IAROSLAVA SNEGIREVA       8.448491     5
    DIANA SOFRONOVA       8.109603     6
     TIKHON ZELENIN       8.081288     7
       SAVVA MARKOV       7.859983     8
       VLAD GOLUBEV       7.104061     9
      ALLA RUSAKOVA       6.969182    10
--------------------------------------------------

,ID,Total_Score,Models_Count,Models_List
16,PETR KOCHETOV,39,5,"IsolationForest, LOF, OneClassSVM, EllipticEnv..."
20,TIMOFEY DRUZHININ,39,4,"LOF, OneClassSVM, EllipticEnvelope, KNN_Distance"
11,MARINA GORELOVA,35,4,"LOF, OneClassSVM, EllipticEnvelope, KNN_Distance"
15,OLEG ANTIPOV,28,4,"IsolationForest, OneClassSVM, EllipticEnvelope..."
3,DIANA SOFRONOVA,20,4,"IsolationForest, OneClassSVM, EllipticEnvelope..."
1,ALLA RUSAKOVA,13,3,"IsolationForest, OneClassSVM, KNN_Distance"
7,IAROSLAVA SNEGIREVA,12,2,"OneClassSVM, KNN_Distance"
24,VLAD GOLUBEV,11,3,"IsolationForest, OneClassSVM, KNN_Distance"
18,SAVVA MARKOV,9,3,"IsolationForest, OneClassSVM, KNN_Distance"
19,TIKHON ZELENIN,8,2,"OneClassSVM, KNN_Distance"
12,MARINA MURAVEVA,8,1,EllipticEnvelope
22,VADIM PLATONOV,8,1,LOF
0,ALENA PETUKHOVA,6,1,EllipticEnvelope
21,ULIANA EROFEEVA,6,1,LOF
9,LILIYA ZOTOVA,5,1,LOF
13,MILENA ZAYTSEVA,5,1,IsolationForest
17,RADMIR KORNEEV,4,1,IsolationForest
25,YASMINA ANISIMOVA,4,1,LOF
6,FEDOR SEREBRYAKOV,3,1,LOF
23,VERA BOGOMOLOVA,3,1,EllipticEnvelope
4,EDUARD PAVLOVSKII,2,1,EllipticEnvelope
8,INNA CHERNYKH,2,1,LOF
10,MADINA LOSEVA,2,1,IsolationForest
2,ANZHELIKA BELIKOVA,1,1,IsolationForest
5,EMIL' SHESTAKOV,1,1,LOF
14,NIKA CHERNYAEVA,1,1,EllipticEnvelope

In [10]:
df = pd.read_csv("../resources/loyalty_flights.csv", sep="|")

df = df.dropna(subset=['Name'])

aggregation_rules = {
    'FirstName': 'mean',
    'LastName': 'mean',
    'Departure': 'mean',
    'Arrival': 'mean',
    'Fare': 'mean',
    'LoyaltyOperationalMatch': 'mean',
    'Codeshare': 'mean',
    'boardFlightMatch': 'mean',
    'FlightOperationalMatch': 'mean',
    'SirenaFlightsMatch': 'mean',
    'BonusProgramA': 'sum',
    'BonusProgramD': 'sum',
    'BonusProgramK': 'sum',
    'BonusProgramFB': 'sum',
    'Flight_DayOfWeek': 'mean',
    'Flight_Month': 'nunique',
    'Airport': 'mean',
    'City': 'mean',
    'Country': 'mean'
}

passenger_df = df.groupby('Name').agg(aggregation_rules).reset_index()

IDS = passenger_df['Name'].copy()
X = passenger_df.drop(columns=['Name'])

X = X.fillna(0)

sp = spies_report(X, IDS)
sp.to_csv("loyalty_flights.csv", sep="|", index=False)
display(sp)

Поиск аномалий

/home/kirill/.local/share/pipx/venvs/jupyter/lib/python3.12/site-packages/sklearn/covariance/_robust_covariance.py:793: UserWarning: The covariance matrix associated to your dataset is not full rank
  warnings.warn(

----------------------------------------------------------------------
Подозрительные
----------------------------------------------------------------------

--- IsolationForest ---
                 ID  Anomaly_Score  Rank
IAROSLAVA SNEGIREVA       0.094009     1
      IGNAT DROZDOV       0.075733     2
      ALLA RUSAKOVA       0.071462     3
      PETR KOCHETOV       0.067970     4
  TIMOFEY DRUZHININ       0.067700     5
   DARINA BELYAKOVA       0.064895     6
      NIKOLAY ZIMIN       0.061566     7
    VALERII NIKITIN       0.060930     8
 VASILIY NIKOL'SKIY       0.060404     9
      DANIEL PANKOV       0.058546    10
--------------------------------------------------

--- LOF ---
                 ID  Anomaly_Score  Rank
  TIMOFEY DRUZHININ       2.644366     1
      PETR KOCHETOV       2.591677     2
STANISLAV VORONTSOV       2.534999     3
   KAMILLA CHERNYKH       2.313437     4
      AMINA OSIPOVA       2.303929     5
       DEMID SHUBIN       2.300780     6
    ARINA DOROFEEVA       2.247405     7
 VALERIYA MEDVEDEVA       2.204392     8
   IAROSLAVA SEMINA       2.168466     9
 NATALIYA FOMICHEVA       2.084040    10
--------------------------------------------------

--- OneClassSVM ---
               ID  Anomaly_Score  Rank
TIMOFEY DRUZHININ       6.421970     1
    PETR KOCHETOV       6.262037     2
MATVEI VESHNIAKOV       6.202936     3
  DIANA SOFRONOVA       5.864123     4
     OLEG ANTIPOV       5.819752     5
    ZAKHAR VOLKOV       5.736872     6
 DARINA BELYAKOVA       5.565527     7
    ALEKSEI RAKOV       5.533262     8
 EMILIIA EREMEEVA       5.520496     9
     TIMUR MAKEEV       5.484059    10
--------------------------------------------------

--- EllipticEnvelope ---
                ID  Anomaly_Score  Rank
  ZARINA MARKELOVA   3.577332e+06     1
DARINA POZDNYAKOVA   3.577326e+06     2
   GERMAN DIAKONOV   3.577320e+06     3
  VASILIY MALYSHEV   3.575856e+06     4
  LIDIIA NESTEROVA   3.575813e+06     5
 MATVEI VESHNIAKOV   3.574701e+06     6
  ODISSEY BESPALOV   3.527627e+06     7
  DARINA BELYAKOVA   3.527534e+06     8
   ODISSEI ERMILOV   3.527273e+06     9
   ELINA MERKULOVA   3.527209e+06    10
--------------------------------------------------

--- KNN_Distance ---
                ID  Anomaly_Score  Rank
   ARINA DOROFEEVA      11.431442     1
  DARINA BELYAKOVA      11.345540     2
     ZAKHAR VOLKOV      11.286652     3
VALERIYA MEDVEDEVA      11.045757     4
 VIOLETTA SOLOVEVA      11.009948     5
  EMILIIA EREMEEVA      10.863867     6
 MATVEI VESHNIAKOV      10.739786     7
   VALERII NIKITIN      10.707321     8
    NIKITA ERMILOV      10.581138     9
     NIKOLAY ZIMIN      10.525028    10
--------------------------------------------------

,ID,Total_Score,Models_Count,Models_List
26,TIMOFEY DRUZHININ,26,3,"IsolationForest, LOF, OneClassSVM"
24,PETR KOCHETOV,25,3,"IsolationForest, LOF, OneClassSVM"
5,DARINA BELYAKOVA,21,4,"IsolationForest, OneClassSVM, EllipticEnvelope..."
17,MATVEI VESHNIAKOV,17,3,"OneClassSVM, EllipticEnvelope, KNN_Distance"
3,ARINA DOROFEEVA,14,2,"LOF, KNN_Distance"
33,ZAKHAR VOLKOV,13,2,"OneClassSVM, KNN_Distance"
29,VALERIYA MEDVEDEVA,10,2,"LOF, KNN_Distance"
13,IAROSLAVA SNEGIREVA,10,1,IsolationForest
34,ZARINA MARKELOVA,10,1,EllipticEnvelope
6,DARINA POZDNYAKOVA,9,1,EllipticEnvelope
14,IGNAT DROZDOV,9,1,IsolationForest
1,ALLA RUSAKOVA,8,1,IsolationForest
11,GERMAN DIAKONOV,8,1,EllipticEnvelope
25,STANISLAV VORONTSOV,8,1,LOF
10,EMILIIA EREMEEVA,7,2,"OneClassSVM, KNN_Distance"
8,DIANA SOFRONOVA,7,1,OneClassSVM
15,KAMILLA CHERNYKH,7,1,LOF
30,VASILIY MALYSHEV,7,1,EllipticEnvelope
28,VALERII NIKITIN,6,2,"IsolationForest, KNN_Distance"
2,AMINA OSIPOVA,6,1,LOF
16,LIDIIA NESTEROVA,6,1,EllipticEnvelope
23,OLEG ANTIPOV,6,1,OneClassSVM
32,VIOLETTA SOLOVEVA,6,1,KNN_Distance
20,NIKOLAY ZIMIN,5,2,"IsolationForest, KNN_Distance"
7,DEMID SHUBIN,5,1,LOF
22,ODISSEY BESPALOV,4,1,EllipticEnvelope
0,ALEKSEI RAKOV,3,1,OneClassSVM
12,IAROSLAVA SEMINA,2,1,LOF
19,NIKITA ERMILOV,2,1,KNN_Distance
21,ODISSEI ERMILOV,2,1,EllipticEnvelope
31,VASILIY NIKOL'SKIY,2,1,IsolationForest
4,DANIEL PANKOV,1,1,IsolationForest
9,ELINA MERKULOVA,1,1,EllipticEnvelope
18,NATALIYA FOMICHEVA,1,1,LOF
27,TIMUR MAKEEV,1,1,OneClassSVM

In [11]:
df = pd.read_csv("SPIES.csv", sep="|")

aggregation_rules = {
    'Score': 'sum',
    'ModelsCount': 'sum',
    'File': lambda x: ', '.join(x.astype(str))
}

df = df.groupby('Data').agg(aggregation_rules).reset_index()
df = df.sort_values(by='Score', ascending=False).reset_index(drop=True)

df.to_csv("SPIES_ready.csv", sep="|", index="false")
df

,Data,Score,ModelsCount,File
0,8007 894293,71,8,"flights_boarding.csv , boarding_operational...."
1,TIMOFEY DRUZHININ,65,7,"loyality_operational.csv, loyality_flights.csv"
2,PETR KOCHETOV,64,8,"loyality_operational.csv, loyality_flights.csv"
3,DANILOVNA VASILISA CHERNYKH,55,8,"boarding.csv , sirena.csv"
4,2211 426963,49,9,"flights_boarding.csv , boarding_operational...."
5,0241 175441,46,7,"flights_boarding.csv , boarding_operational...."
6,MARINA GORELOVA,35,4,loyality_operational.csv
7,5293 500602,35,4,pass_boarding.csv
8,8421 352449,31,5,boarding_operational.csv
9,OLEG ANTIPOV,28,4,loyality_operational.csv
10,3710 150996,27,4,boarding_operational.csv
11,1381 919028,27,3,pass_boarding.csv
12,ANDREEVICH GORDEI CHERNYKH,25,3,boarding.csv
13,2908 898279,25,3,flights_boarding.csv
14,9579 067482,25,3,pass_boarding.csv
15,5058 032032,25,4,flights_boarding.csv
16,PLATONOVNA KIRA DANILOVA,24,3,sirena.csv
17,LVOVICH ALEKSANDR KHROMOV,23,3,sirena.csv
18,MAKAREVNA KARINA CHERNYKH,22,3,boarding.csv
19,DARINA BELYAKOVA,21,4,loyality_flights.csv
20,SEMENOVICH NAZAR SYCHEV,21,3,sirena.csv
21,ROBERTOVNA ALLA SHEVTSOVA,20,3,sirena.csv
22,ARSENEVICH RADMIR GOLUBEV,20,3,sirena.csv
23,DANILOVICH ALEKSEI PARAMONOV,20,3,sirena.csv
24,DIANA SOFRONOVA,20,4,loyality_operational.csv
25,8296 978071,19,3,pass_boarding.csv
26,0548 488693,19,3,pass_boarding.csv
27,ARSENEVNA NATALIIA ZYKOVA,18,3,boarding.csv
28,4819 170172,16,4,boarding_operational.csv
29,ARSENEVNA IASMINA DAVYDOVA,15,3,sirena.csv
30,6477 314549,14,2,pass_boarding.csv
31,ALLA RUSAKOVA,13,3,loyality_operational.csv
32,6298 955090,13,3,pass_boarding.csv
33,ARSENEVNA VASILISA EREMINA,10,1,boarding.csv
34,6025 719450,10,1,flights_boarding.csv
35,0016 277417,10,1,flights_boarding.csv
36,1978 571330,9,1,boarding_operational.csv
37,2468 127099,9,1,flights_boarding.csv
38,5294 379207,9,1,boarding_operational.csv
39,4325 574940,9,1,pass_boarding.csv
40,DANILOVNA NATALIA TROSHINA,9,1,boarding.csv